SELECT * from movie where name ilike '%the clone wars%';
SELECT * from movie where name ilike '%The Last Airbender The%';
SELECT * from movie where name ilike '%The Last Airbender%';
SELECT * from movie where name ilike '%bandof%';;
SELECT * from movie where name ilike '%korra%';
SELECT * from movie where name ilike '%mandalorian%';
SELECT * from movie where name ilike '%falling.skies%';
SELECT * from movie where name ilike '%ducktales%';
SELECT * from movie where name ilike '%The Pirates Of Dark%';
SELECT * from movie where name ilike '%Tales From Earthsea%';
SELECT * from movie where name ilike '%War Of The Worlds BBC%';
SELECT * from movie where name ilike '%Falling Skies%';
UPDATE movie SET genre = 'TV' where name ilike '%The Last Airbender%';
UPDATE movie SET genre = 'TV' where name ~ '^\d{3} ';
UPDATE movie SET genre = 'TV' where name ilike '%the clone wars%';
UPDATE movie SET genre = 'TV' where name ilike '%mandalorian%';
UPDATE movie SET genre = 'TV' where name ilike '%bandof%';
UPDATE movie SET genre = 'TV' where name ilike '%korra%';
UPDATE movie SET genre = 'TV' where name ilike '%PAW%';
UPDATE movie SET genre = 'TV' where name ilike '%talespin%';
UPDATE movie SET genre = 'TV' where name ilike '%falling.skies%';
UPDATE movie SET genre = 'TV' where name ilike '%ducktales%';
UPDATE movie SET genre = 'TV' where name ilike '%The Pirates Of Dark%';
UPDATE movie SET genre = 'TV' where name ilike '%Tales From Earthsea%';
UPDATE movie SET genre = 'TV' where name ilike '%War Of The Worlds BBC%';
UPDATE movie SET genre = 'TV' where name ilike '%Falling Skies%';